### ISSUE TITLE
42 인증 로그인 작업..

### ISSUE THREAD

**Issue by shimyounghyun** [shimyounghyun/42-sns#13]
로그인 연동에 어려움을 겪고있습니다.
1. graphql에 passport를 적용하는 방법을 모르겠습니다.
    - rest api처럼 접근이 다양한 경우 대응할 수 있지만, graphql은 단일 경로

2. api 직접 호출은 서버에서 이루어져야 하고(`this request must be performed on server side, over a secure connexion`), 값을 받는 경로 또한 서버일 수 밖에 없습니다.
   - graphql에서 router를 사용해 콜백 주소를 만들 수 있는지 확인이 필요합니다.

#### 1. `앱 공개키`, `콜백 주소` 를 통해 `콜백 주소`로 `code`값을 받습니다. 
`앱 공개키`  : 42 앱 생성시 발급받는 공개 키
`콜백 주소`  : 로그인 처리를 하게될 우리 사이트의 주소

#### 2. `인증 형식`, `앱 비밀키`, `앱 공개키`, `code`를 통해 `콜백 주소`로  `access_token`을 받습니다.
```
`콜백 주소`는 required가 아니지만 `콜백주소`를 넣어야 제대로된 `access_token`을 받을 수 있습니다.
```
`인증 형식` : authorization_code (고정값) 
`앱 비밀키` : 42 앱 생성시 발급 받는 비공개 키
`앱 공개키`  : 42 앱 생성시 발급받는 공개 키
`code` : 1단계에서 획득한 암호화된 문자열

#### 3. `access_token`을 통해 회원 기본정보를 `콜백 주소`로 받아올 수 있습니다.
`access_token` : 2단계에서 발급 받은 암호화된 문자열로, 인트라 로그인한 계정의 정보를 볼 수 있다.

**Comment by DomMorello** [comment]
확인했습니다.

**Comment by shimyounghyun** [comment]
client에서 code를 받고 server로 code값을 넘겨주는 방식으로 해결!
